#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Capability contract validator (ADR-0001 #7).

Single source of truth: ``05-Tools/capabilities.json``.
``05-Tools/CAPABILITY-MATRIX.md`` is a derived view: its three capability
tables live inside ``<!-- MATRIX:BEGIN -->`` / ``<!-- MATRIX:END -->`` and are
regenerated by ``--render-matrix``. Maintenance flow: edit JSON → render → commit.

Usage:
  python scripts/capability-check.py [--verbose]      # live-verify every capability
  python scripts/capability-check.py --check-drift    # JSON vs Markdown set comparison
  python scripts/capability-check.py --render-matrix  # regenerate MD tables from JSON
"""

import sys

# Prevent Windows GBK stdout/stderr trap (RFC / Vault Standard MUST)
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

import argparse
import json
import pathlib
import subprocess

VAULT_ROOT = pathlib.Path(__file__).resolve().parent.parent
CAPABILITIES_PATH = VAULT_ROOT / "05-Tools" / "capabilities.json"
MATRIX_PATH = VAULT_ROOT / "05-Tools" / "CAPABILITY-MATRIX.md"

SCHEMA_VERSION = 1
LEGAL_STATUS = ("verified", "configured", "degraded")
REQUIRED_FIELDS = (
    "name", "type", "tier", "verification_command",
    "declared_status", "section", "scope", "confirmation_required",
)
DRIFT_KEY_FIELDS = ("name", "type", "tier", "verification_command")
MATRIX_BEGIN = "<!-- MATRIX:BEGIN -->"
MATRIX_END = "<!-- MATRIX:END -->"
MATRIX_LISTING_HEADING = "## 能力清单"

# Deterministic render layout: one marker pair wrapping all three sections,
# each section rendered in the JSON array order of its capabilities.
SECTION_TITLES = (
    ("scripts", "### Scripts（脚本）"),
    ("mcp", "### MCP Services（MCP 服务）"),
    ("skills", "### Skills（技能，清理后）"),
)


def load_capabilities(json_path: pathlib.Path | str) -> list:
    """Load capabilities.json — the single source of truth — enforcing the schema.

    Raises ValueError on any contract violation: a missing schema field, an
    unknown declared_status, a scope other than "read-only", or a capability
    claiming verified/degraded without a verification_command.
    """
    data = json.loads(pathlib.Path(json_path).read_text(encoding="utf-8"))
    if data.get("schema_version") != SCHEMA_VERSION:
        raise ValueError(f"{json_path}: schema_version must be {SCHEMA_VERSION}")
    capabilities = []
    for cap in data.get("capabilities", []):
        missing = [field for field in REQUIRED_FIELDS if field not in cap]
        if missing:
            raise ValueError(f"capability {cap.get('name', '?')}: missing fields {missing}")
        if cap["declared_status"] not in LEGAL_STATUS:
            raise ValueError(
                f"capability {cap['name']}: unknown declared_status "
                f"{cap['declared_status']!r} (legal: {', '.join(LEGAL_STATUS)})"
            )
        if cap["scope"] != "read-only":
            raise ValueError(f"capability {cap['name']}: scope must be 'read-only'")
        if cap["verification_command"] is None and cap["declared_status"] != "configured":
            raise ValueError(
                f"capability {cap['name']}: no verification_command but declared "
                f"{cap['declared_status']!r} — only 'configured' is honest without a verifier"
            )
        capabilities.append(cap)
    return capabilities


def parse_matrix(matrix_path: pathlib.Path) -> list:
    """Parse CAPABILITY-MATRIX.md — kept as the Markdown side of --check-drift."""
    content = matrix_path.read_text(encoding="utf-8")
    capabilities = []

    # Find all table rows with verification_command
    for line in content.split("\n"):
        if not line.startswith("|") or "---" in line or "能力" in line:
            continue
        parts = [p.strip() for p in line.split("|") if p.strip()]
        if len(parts) >= 5:
            name = parts[0]
            cap_type = parts[1]
            tier = parts[2]
            # Cell is markdown-formatted: `cmd`. Backticks MUST be stripped or
            # shell=True treats them as command substitution (false "degraded").
            raw = parts[3].strip("`").strip()
            verify_cmd = raw if raw != "—" else None
            status = parts[4]
            capabilities.append({
                "name": name,
                "type": cap_type,
                "tier": tier,
                "verification_command": verify_cmd,
                "declared_status": status,
            })

    return capabilities


def drift_key(cap: dict) -> tuple:
    """Alignment key for --check-drift: (name, type, tier, verification_command)."""
    return tuple(cap[field] for field in DRIFT_KEY_FIELDS)


def drift_report(json_caps: list, md_caps: list) -> list:
    """Human-readable drift lines between the JSON truth and the Markdown view.

    An empty list means the two sets are aligned on the drift key.
    """
    json_keys = {drift_key(cap) for cap in json_caps}
    md_keys = {drift_key(cap) for cap in md_caps}
    report = []
    for key in sorted(json_keys - md_keys, key=repr):
        report.append(f"missing-in-matrix: {key[0]!r} (type={key[1]}, tier={key[2]}, cmd={key[3]!r})")
    for key in sorted(md_keys - json_keys, key=repr):
        report.append(f"missing-in-json:   {key[0]!r} (type={key[1]}, tier={key[2]}, cmd={key[3]!r})")
    return report


def render_tables(caps: list) -> str:
    """Render the three capability tables inside one marker pair."""
    lines = [MATRIX_BEGIN, ""]
    for section_key, title in SECTION_TITLES:
        lines.append(title)
        lines.append("")
        lines.append("| 能力 | 类型 | tier | verification_command | 状态 |")
        lines.append("| --- | --- | --- | --- | --- |")
        for cap in caps:
            if cap["section"] != section_key:
                continue
            cmd = cap["verification_command"]
            cell = f"`{cmd}`" if cmd else "—"
            lines.append(
                f"| {cap['name']} | {cap['type']} | {cap['tier']} | {cell} | {cap['declared_status']} |"
            )
        lines.append("")
    lines.append(MATRIX_END)
    return "\n".join(lines)


def _insert_marker_block(text: str, block: str) -> str:
    """First render: wrap the 能力清单 section body (the section heading stays outside)."""
    lines = text.split("\n")
    section_idx = None
    for idx, line in enumerate(lines):
        if line.strip() == MATRIX_LISTING_HEADING:
            section_idx = idx
            break
    if section_idx is None:
        raise ValueError(f"matrix is missing the {MATRIX_LISTING_HEADING!r} heading")
    next_heading_idx = len(lines)
    for idx in range(section_idx + 1, len(lines)):
        if lines[idx].startswith("## "):
            next_heading_idx = idx
            break
    return "\n".join(lines[:section_idx + 1] + ["", block, ""] + lines[next_heading_idx:])


def render_matrix(matrix_path: pathlib.Path, caps: list) -> bool:
    """Regenerate the marker-wrapped tables from JSON. Returns True when bytes changed."""
    text = matrix_path.read_text(encoding="utf-8")
    block = render_tables(caps)
    begin_idx = text.find(MATRIX_BEGIN)
    end_idx = text.find(MATRIX_END)
    if begin_idx == -1 and end_idx == -1:
        new_text = _insert_marker_block(text, block)
    elif begin_idx != -1 and end_idx != -1 and end_idx > begin_idx:
        new_text = text[:begin_idx] + block + text[end_idx + len(MATRIX_END):]
    else:
        raise ValueError("CAPABILITY-MATRIX.md has a broken MATRIX marker pair")
    if new_text == text:
        return False
    # newline="" preserves the file's LF endings byte-for-byte on Windows.
    matrix_path.write_text(new_text, encoding="utf-8", newline="")
    return True


def check_capability(cap: dict, verbose: bool = False) -> str:
    """Run verification command and return actual status."""
    cmd = cap["verification_command"]
    if not cmd:
        return "configured"

    try:
        result = subprocess.run(
            cmd,
            shell=True,
            cwd=str(VAULT_ROOT),
            capture_output=True,
            timeout=30,
        )
        if verbose:
            print(f"  [{cap['name']}] exit={result.returncode}")
        return "verified" if result.returncode == 0 else "degraded"
    except subprocess.TimeoutExpired:
        if verbose:
            print(f"  [{cap['name']}] TIMEOUT")
        return "degraded"
    except Exception as e:
        if verbose:
            print(f"  [{cap['name']}] ERROR: {e}")
        return "degraded"


def _cmd_check_drift() -> int:
    """Compare capabilities.json against CAPABILITY-MATRIX.md; 1 on drift."""
    json_caps = load_capabilities(CAPABILITIES_PATH)
    md_caps = parse_matrix(MATRIX_PATH)
    report = drift_report(json_caps, md_caps)
    if report:
        print(f"❌ Capability drift: capabilities.json vs CAPABILITY-MATRIX.md ({len(report)}):")
        for line in report:
            print(f"  {line}")
        return 1
    print(f"✅ No drift: {len(json_caps)} capabilities aligned between "
          f"capabilities.json and CAPABILITY-MATRIX.md.")
    return 0


def _cmd_render_matrix() -> int:
    """Regenerate the matrix tables from the JSON source; idempotent."""
    caps = load_capabilities(CAPABILITIES_PATH)
    changed = render_matrix(MATRIX_PATH, caps)
    if changed:
        print("♻️ Matrix tables regenerated from capabilities.json "
              "(maintenance flow: edit JSON → render → commit).")
    else:
        print("✅ Matrix tables already up to date (idempotent render).")
    return 0


def _cmd_verify(verbose: bool) -> int:
    """Live-verify every capability declared in the JSON source."""
    if not CAPABILITIES_PATH.exists():
        print(f"❌ Capabilities source not found: {CAPABILITIES_PATH}")
        return 1

    capabilities = load_capabilities(CAPABILITIES_PATH)
    if not capabilities:
        print("❌ No capabilities found in capabilities.json")
        return 1

    print(f"📋 Checking {len(capabilities)} capabilities...\n")

    results = {"verified": 0, "configured": 0, "degraded": 0}
    mismatches = []

    for cap in capabilities:
        actual = check_capability(cap, verbose)
        results[actual] += 1

        if actual != cap["declared_status"]:
            mismatches.append((cap["name"], cap["declared_status"], actual))

        status_icon = {"verified": "✅", "configured": "⚙️", "degraded": "⚠️"}
        print(f"  {status_icon[actual]} {cap['name']}: {actual}")

    print(f"\n📊 Summary: {results['verified']} verified, {results['configured']} configured, {results['degraded']} degraded")

    if mismatches:
        print(f"\n⚠️ {len(mismatches)} status mismatches:")
        for name, declared, actual in mismatches:
            print(f"  {name}: declared={declared}, actual={actual}")
        return 1

    print("\n✅ All capabilities match their declared status.")
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Capability contract validator (source of truth: capabilities.json)"
    )
    parser.add_argument("--verbose", "-v", action="store_true",
                        help="print per-command exit codes during live verification")
    parser.add_argument("--check-drift", action="store_true",
                        help="compare capabilities.json with CAPABILITY-MATRIX.md; exit 1 on drift")
    parser.add_argument("--render-matrix", action="store_true",
                        help="regenerate the CAPABILITY-MATRIX.md tables from capabilities.json")
    args = parser.parse_args()

    if args.check_drift:
        sys.exit(_cmd_check_drift())
    if args.render_matrix:
        sys.exit(_cmd_render_matrix())
    sys.exit(_cmd_verify(args.verbose))


if __name__ == "__main__":
    main()
