#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Unified Audit Log Writer for Coding Vault (11-Agents/logs/YYYY-MM.md)
=====================================================================
Single source of truth for appending agent-audit rows into month-sharded
log files. All scripts that record audit entries MUST import this module
instead of re-implementing their own append logic (anti-drift invariant,
see 01-Rules/SKILL-AUTHORING-SPEC §7 single-source spirit).

Behavior:
  1. Resolves target as  11-Agents/logs/{YYYY-MM}.md  (current month).
  2. Creates file with compliant YAML frontmatter + table header if missing.
  3. Inserts one row  | ts | agent | op | paths | summary |  into the audit
     table block, keeping the table contiguous above any trailing prose.
  4. UTF-8 stdout/file protection for Windows.

Usage from scripts/:
    from vault_audit import append_audit_row
    ok, msg = append_audit_row(vault_root, "CodeBuddy (Specialist)",
                               "Audit & Healthcheck", "`paths`", "<br>summary")
"""

import os
import pathlib
import re
import sys
from datetime import datetime

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

# Table structure shared with 11-Agents/logs/*.md (generated by migration).
AUDIT_TABLE_HEADER = (
    "| 时间戳 | Agent / 角色 | 操作类型 | 受影响路径 | 操作摘要 & 验证 |\n"
    "| :--- | :--- | :--- | :--- | :--- |\n"
)


def _frontmatter(ym: str) -> str:
    """Build compliant YAML frontmatter + intro for a fresh month file."""
    today = datetime.now().strftime("%Y-%m-%d")
    return (
        "---\n"
        f'title: "Agent 操作审计日志 — {ym}"\n'
        f"created: {today}\n"
        f"updated: {today}\n"
        "type: rules\n"
        "tags:\n"
        "  - category/audit\n"
        "  - category/agent\n"
        "status: stable\n"
        "audience: both\n"
        "---\n\n"
        f"# Agent 操作审计日志 — {ym}\n\n"
        "> 本文为 [[11-Agents/review-log]] 的按月分片明细，逐行字段含义见 "
        "review-log「日志记录规范」。\n\n"
        "## 审计日志表\n\n"
    )


def _insert_into_table(content: str, row: str) -> str:
    """Insert a data row into the audit table, keeping the table contiguous.

    Canonical shard layout: frontmatter -> "## 审计日志表" -> header
    -> separator (| :--- |) -> data rows -> optional prose paragraphs.
    A bare end-of-file append would drop the row below trailing prose and
    break the Markdown table, so the row is inserted right after the last
    contiguous data row. Falls back to raw append when no table exists.
    """
    lines = content.split("\n")
    sep = next((i for i, ln in enumerate(lines)
                if ln.lstrip().startswith("| :---")), None)
    if sep is None:  # no table yet — raw append
        text = content
        if text and not text.endswith("\n"):
            text += "\n"
        return text + row
    j = sep + 1
    while j < len(lines) and lines[j].lstrip().startswith("|"):
        j += 1
    lines.insert(j, row.rstrip("\n"))
    return "\n".join(lines)


def append_audit_row(vault_root, agent_name, op_type, paths_str, summary_cell,
                     timestamp=None):
    """Append one audit table row to the current month's shard file.

    Args:
        vault_root: vault root path (pathlib.Path or str).
        agent_name: e.g. "CodeBuddy (Vault Skill Governance Specialist)".
        op_type:    e.g. "Audit & Healthcheck".
        paths_str:  affected path cell content, e.g. "`scripts/x.py`".
        summary_cell: summary cell content (may contain "<br>"), no "|" row wrap.
        timestamp: optional str; defaults to now "%Y-%m-%d %H:%M".

    Returns:
        (ok: bool, message: str)
    """
    root = pathlib.Path(vault_root).resolve()
    logs_dir = root / "11-Agents" / "logs"
    if not (root / "AGENTS.md").exists():
        return False, f"❌ {root} is not a vault root (AGENTS.md missing)."

    try:
        logs_dir.mkdir(parents=True, exist_ok=True)
        ts = timestamp or datetime.now().strftime("%Y-%m-%d %H:%M")
        ym = ts[:7]  # YYYY-MM
        target = logs_dir / f"{ym}.md"

        if not target.exists():
            target.write_text(_frontmatter(ym) + AUDIT_TABLE_HEADER,
                              encoding="utf-8")

        # Guard: caller summary must not smuggle raw pipe rows in.
        if "\n" in summary_cell or "|" in summary_cell:
            summary_cell = summary_cell.replace("|", "\\|").replace("\n", " ")

        row = f"| {ts} | {agent_name} | {op_type} | {paths_str} | {summary_cell} |\n"
        with open(target, "r", encoding="utf-8", errors="replace") as f:
            content = f.read()
        new_content = _insert_into_table(content, row)
        # 原子写（tmp + os.replace）：crash 不再截断当月审计分片（2026-09-11 二评）
        tmp = target.with_suffix(".md.tmp")
        with open(tmp, "w", encoding="utf-8", errors="replace") as f:
            f.write(new_content)
        os.replace(tmp, target)
        return True, f"📝 Audit row inserted into audit table of {target}"
    except Exception as e:  # noqa: BLE001 - explicit surfacing to callers
        return False, f"❌ Failed to append audit row: {e}"


def main() -> int:
    """CLI smoke test: append a sample row to the current month file."""
    if len(sys.argv) < 4:
        print("usage: python vault_audit.py <agent> <op_type> <summary> "
              "[paths] [--vault-path P]")
        return 2
    agent = sys.argv[1]
    op_type = sys.argv[2]
    summary = sys.argv[3]
    paths = sys.argv[4] if len(sys.argv) > 4 else "`-`"
    root = None
    if "--vault-path" in sys.argv:
        root = sys.argv[sys.argv.index("--vault-path") + 1]
    ok, msg = append_audit_row(root or pathlib.Path(__file__).resolve().parents[1],
                               agent, op_type, paths, summary)
    print(msg)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
